server:
  name: "Grom dev (TLS)"
  port: 8080
  tls:
    mode: static
    port: 8443
    cert_file: tls/server.crt
    key_file: tls/server.key

federation:
  enabled: true
  domain: "192.168.1.251:8443"
  auto_accept_follows: true
  ca_cert_file: tls/ca.crt
  tls_insecure_skip_verify: true

auth:
  jwt_secret: "change-me-in-production-min-32-chars!!"
  jwt_ttl_hours: 24

storage:
  location: data
  temp_dir: tmp

logging:
  level: debug
  format: text
