const defaultHealthSyncSportTypeId = 'Workout';

const _healthSyncSportMap = <String, String>{
  'CYCLING': 'Ride',
  'BIKING': 'Ride',
  'BIKE': 'Ride',
  'RIDE': 'Ride',
  'ROAD_BIKING': 'Ride',
  'RUNNING': 'Run',
  'RUN': 'Run',
  'JOGGING': 'Run',
  'TREADMILL': 'Run',
  'WALKING': 'Walk',
  'WALK': 'Walk',
  'HIKING': 'Hike',
  'HIKE': 'Hike',
  'SWIMMING': 'Swim',
  'SWIM': 'Swim',
  'POOL_SWIMMING': 'Swim',
  'OPEN_WATER_SWIMMING': 'Swim',
  'ROWING': 'Rowing',
  'KAYAKING': 'Kayaking',
  'CANOEING': 'Canoeing',
  'PADDLING': 'Kayaking',
  'SKIING': 'AlpineSki',
  'ALPINE_SKIING': 'AlpineSki',
  'NORDIC_SKIING': 'NordicSki',
  'CROSS_COUNTRY_SKIING': 'NordicSki',
  'SNOWBOARDING': 'Snowboard',
  'SNOWSHOEING': 'Snowshoe',
  'ICE_SKATING': 'IceSkate',
  'INLINE_SKATING': 'InlineSkate',
  'SKATEBOARDING': 'Skateboard',
  'ELLIPTICAL': 'Elliptical',
  'STAIR_CLIMBING': 'StairStepper',
  'STAIR_STEPPER': 'StairStepper',
  'YOGA': 'Yoga',
  'PILATES': 'Pilates',
  'WEIGHT_TRAINING': 'WeightTraining',
  'WEIGHTTRAINING': 'WeightTraining',
  'STRENGTH_TRAINING': 'WeightTraining',
  'STRENGTH': 'WeightTraining',
  'WORKOUT': 'Workout',
  'OTHER': 'Workout',
  'EXERCISE': 'Workout',
  'CROSSFIT': 'Crossfit',
  'HIIT': 'HIIT',
  'GOLF': 'Golf',
  'TENNIS': 'Tennis',
  'BADMINTON': 'Badminton',
  'TABLE_TENNIS': 'TableTennis',
  'SOCCER': 'Soccer',
  'BASKETBALL': 'Basketball',
  'VOLLEYBALL': 'Volleyball',
  'SURFING': 'Surfing',
  'KITESURFING': 'Kitesurf',
  'WINDSURFING': 'Windsurf',
  'SAILING': 'Sail',
  'MOUNTAIN_BIKING': 'MountainBikeRide',
  'MTB': 'MountainBikeRide',
  'GRAVEL_CYCLING': 'GravelRide',
  'GRAVEL': 'GravelRide',
  'E_BIKE': 'EBikeRide',
  'EBIKE': 'EBikeRide',
  'TRAIL_RUNNING': 'TrailRun',
  'TRAIL_RUN': 'TrailRun',
  'WHEELCHAIR': 'Wheelchair',
  'DANCE': 'Dance',
  'ROCK_CLIMBING': 'RockClimbing',
  'HANDBIKING': 'Handcycle',
};

String mapHealthSyncSportType(String rawSport) {
  final normalized = rawSport.trim().toUpperCase().replaceAll(' ', '_');
  return _healthSyncSportMap[normalized] ?? defaultHealthSyncSportTypeId;
}
